### ISSUE TITLE
Github Action failed due to the unit test of TestCluster 

### ISSUE THREAD

**Issue by zhao-kun** [megaease/easegress#111]
### Background

Thank contributors for introducing the Github Action, but all PRs were checked failed by Github Action, apparently, the root cause of failure doesn't relate to the runtime environment of Github Action, as our unit test should be environment-independent.

The following text is a snapshot of checking output about the failure
```
2021-07-08T02:51:50.758Z	ERROR	cluster/cluster.go:679	register cluster name test-cluster failed: create client failed: couldn't open sink "/tmp/eg-test/test-member-001/log/etcd_client.log": open /tmp/eg-test/test-member-001/log/etcd_client.log: no such file or directory
panic: register cluster name test-cluster failed: create client failed: couldn't open sink "/tmp/eg-test/test-member-001/log/etcd_client.log": open /tmp/eg-test/test-member-001/log/etcd_client.log: no such file or directory

goroutine 189 [running]:
github.com/megaease/easegress/pkg/cluster.(*cluster).startServer.func2(0xc0004689a0, 0xc00003e600, 0xc0001cad60, 0xc000121090, 0xc000121098)
	/home/runner/work/easegress/easegress/pkg/cluster/cluster.go:680 +0x43d
created by github.com/megaease/easegress/pkg/cluster.(*cluster).startServer
	/home/runner/work/easegress/easegress/pkg/cluster/cluster.go:668 +0x35b
FAIL	github.com/megaease/easegress/pkg/cluster	0.655s
```

### Expectation

All the Github Action run check normally

### Possible solution

It's wrong to use a tmporay directory with a specific directory.  I strongly recommend `ioutil.TempDir(os.TempDir(), prefix)` instead of using `mkdir("/tmp" + prefix)`

We can easily reproduce the issue with `make build-docker`,  but we need slightly modify `build/package/Dockerfile` with 

```diff
diff --git a/build/package/Dockerfile b/build/package/Dockerfile
index eccdafa..39ff169 100644
--- a/build/package/Dockerfile
+++ b/build/package/Dockerfile
@@ -1,10 +1,10 @@
-FROM golang:alpine AS builder
-RUN apk --no-cache add make git
+FROM golang AS builder
+#RUN apk --no-cache add make git

 WORKDIR /opt/easegress
 COPY . .

-RUN make clean && make build
+RUN make clean && make test && make build

```

**Comment by benja-wu** [comment]
@zhao-kun  Thanks for the suggestion. 
* I am working on open an issue for the Easegress cluster behaviour changing proposal which can help to solve the cluster testing failure in Github testing env. (Changing to ETCD cluster solution directly or continuing improving current cluster implementation. Should comparing with other distributing productions' solutions.)
* Speaking about the cluster test case failure
```bash
register cluster name test-cluster failed: create client failed: couldn't open sink "/tmp/eg-test/test-member-001/log/etcd_client.log": open /tmp/eg-test/test-member-001/log/etcd_client.log: no such file or directory
```
It's weird to me that it can't be reproduced successfully every time in my development env. And sometimes the Github test can successfully go through too! If the tmp directory is the root cause, it should be failed every time. Or maybe Github testing don't run in the same docker-backend every time? 

## Summary
1. I will change the directory to `os.TempDir` in this test case. 
2. The issue for Easegress cluster behaviour is still necessary.

**Comment by zhao-kun** [comment]
> We can easily reproduce the issue with `make build-docker`,  but we need slightly modify `build/package/Dockerfile` with 
> ```diff
> diff --git a/build/package/Dockerfile b/build/package/Dockerfile
> index eccdafa..39ff169 100644
> --- a/build/package/Dockerfile
> +++ b/build/package/Dockerfile
> @@ -1,10 +1,10 @@
> -FROM golang:alpine AS builder
> -RUN apk --no-cache add make git
> +FROM golang AS builder
> +#RUN apk --no-cache add make git
>
> WORKDIR /opt/easegress
> COPY . .
>
>-RUN make clean && make build
>+RUN make clean && make test && make build

>```
