### ISSUE TITLE
The APIAggregator does not work

### ISSUE THREAD

**Issue by zhongdonglin** [megaease/easegress#149]
```go
func init() {
	// FIXME: Rewrite APIAggregator because the HTTPProxy is eliminated
	// I(@xxx7xxxx) think we should not empower filter to cross pipelines.

	// httppipeline.Register(&APIAggregator{})
}
```

I saw this in code, Is this function still to be developed? I think it is very useful ！Thanks

**Comment by benja-wu** [comment]
> func init() {
> // FIXME: Rewrite APIAggregator because the HTTPProxy is eliminated
> // I(@xxx7xxxx) think we should not empower filter to cross pipelines.
> 
> ```
> // httppipeline.Register(&APIAggregator{})
> ```
> 
> }
> 
> I saw this in code, Is this function still to be developed? I think it is very useful ！Thanks

Hi @zhongdonglin, yes,  the API aggregator can't work as expected currently due to the architecture upgrade and refactor.

1. We had eliminated `HTTPProxy` from Easegress. We need to replace it with `HTTPPipeline`. 
2. The purpose of the API Aggregator filter is to forward the original HTTP request to one or several other pipelines inside the same namespace. (Yes,  Easegresss has `namespace` concept now), then combined the results together. I think this behavior is acceptable since it is requesting an existing pipeline for handling a request.

So I will open a PR to repair the API Aggregator, and make it works again. Thx

**Comment by xxx7xxxx** [comment]
Besides the reasons @benja-wu said, in the code comment as I said, it used the cross-pipelines feature which brings unpredictable behaviors IMO. So the feature will be completed ASAP. Thx!
