### ISSUE TITLE
How to extend service discovery without recompiling ？

### ISSUE THREAD

**Issue by brzyangg** [megaease/easegress#185]
The Service Registry used internally by our company is currently etcd. 

I see that there is an EtcdServiceRegistry. But the data structure we store now does not correspond to the structure needed to access the registry. So I want to develop a service discovery that can parse our structure. I understand that if I add my code directly to the source code, I need to recompile to use my service discovery. 

So, I want to ask if there are other ways to meet my needs

**Comment by benja-wu** [comment]
HI @brzyangg
The answer is `NO`. 

But there are some background details I would like to  discuss with u: 
* First of all, the current `EtcdServiceRegistry` will get all the records in a configurable prefix and find the target service's, but it expects the record data in [this stucture](https://github.com/megaease/easegress/blob/main/pkg/object/serviceregistry/service.go#L40) YAML or JSON format. 
* If we want to keep Easegress functional for your Etcd registry, how about adding an adapting layer to transform your system's record into a new prefix which can be chosen by yourself and with the Easegress wanted data format? 

PS: this external service registry works for the `proxy` filter's instance IP pool currently.

**Comment by brzyangg** [comment]
Hi，@benja-wu 
Understood, thank you for your answer.
Yes, Actually I want to use our structure. Because we have used this structure extensively.
May not support now. But will it be supported in the future?
For example, by registering `an external controller` or `input data schema`.

**Comment by benja-wu** [comment]
> Hi，@benja-wu
> Understood, thank you for your answer.
> Yes, Actually I want to use our structure. Because we have used this structure extensively.
> May not support now. But will it be supported in the future?
> For example, by registering `an external controller` or `input data schema`.

Emm.. Is the `external controller` is the Kubernetes `CRD` sort thing? If so,  I think that's beyond Easegress' scope.
But as to the `input data schema` proposal, according to our Easegress product principles, it does need to be `Opening & Extensibility`. So maybe we can use `WASM`'s ability for handling customizing data adapting for `EtcdServiceRegistry`.

It may look like this:
* Users provide customizing data serialization & deserialization code logic in their familiar language and compile them into WASM format.
* Easegress' `ServiceRegistry` invokes this WASM logic to transform the user's system's Etcd/Consul/Nacos records into the Easegress wanted format. 

That's just a draft and quick brainstorm, need to be figured out more detailly and clearly. And a completed design is also needed.  

PS: Since Easegress is an open-source project, maybe we can start this cool feature by writing a design issue first, its background, pros/cons, proposal, dataflow, etc...  :-)

**Comment by zhao-kun** [comment]
X problem is how to integrate with external Service Discovery service. I think it's a true requirement. and now we are working on it, but I think we may abstract a service registry driver to hidden details of a specific  Service discovery service and we can develop a mechanism to handle (or mapping) different memory layouts.

**Comment by benja-wu** [comment]
> X problem is how to integrate with external Service Discovery service. I think it's a true requirement and now we are working on it, but I think we may abstract a service registry driver to hidden details of a specific Service discovery service and we can develop a mechanism to handle (or mapping) different memory layouts.

Yes, ` a mechanism to handle (or mapping) different memory layouts` is what we needed for solving this X problem.
Easegress does support external service discovery right now.

So I prefer to open a new design issue for this `transforming mechanism`. I strongly recommend using `WASM` since we had done some basic support in the `WASMHost` filter already. Maybe there is a better solution, we need to figure it out. :-)

**Comment by brzyangg** [comment]
Thank you for your suggestions, I will try the WASM solution

**Comment by benja-wu** [comment]
Since we had figured out the X problem is the `input data schema supporting mechanism` here,  I will close this discussion one and open a new design issue.
If u @brzyangg  are also interested, welcome to open it and contribute to this feature's design and implementation. :-)
