### ISSUE TITLE
ERROR   cluster/cluster.go:203  failed start many times(199), start others if they're not online, otherwise purge this member, clean data directory and rejoin it back.

### ISSUE THREAD

**Issue by llooper-dev** [megaease/easegress#268]
ERROR   cluster/cluster.go:203  failed start many times(199), start others if they're not online, otherwise purge this member, clean data directory and rejoin it back.

**Comment by localvar** [comment]
hi @llooper-dev , this is just a message to report an error,  but to find out what caused this error, we need more information, such as:

* what is the configuration?
* which version of Easegress are you using?
* what's your environment, like the OS version.
* is it deployed as a cluster?
* what have you done before seeing this error?
* can you reproduce it? if yes, please include the steps in the issue.
* ...

provide this information could help us to find the root cause more quickly.

**Comment by localvar** [comment]
close as the issue is staled for more than a year.
