### ISSUE TITLE
pressure test report 

### ISSUE THREAD

**Issue by gw123** [megaease/easegress#310]
![image](https://user-images.githubusercontent.com/13729169/137864983-9e952bbc-4c7b-4db6-8a0b-ba044ef8a24a.png)

 目前来看单pod在10-200ms 相应 qps可以到 11000左右，  极限情况在可以抗住1.3-1.5w左右qps 3分钟左右 ，在qps到 9000 或者 cpu 到60%需要做扩容 否则程序可以重启。
 在10个pod情况下由于后端负载在压力大情况下返回延迟会变大 在3.8 qps 压力下到顶，在多的压力网关qps反而会下降。

感觉需要优化的地方，希望大佬给一点建议
1. easegress 网关在后端接口返回时间比较长的情况下性能下降比较厉害
2. easegress 网关在达到顶峰压力后，在新增压力性能会下降到很低的水平

**Comment by localvar** [comment]
under high pressure, this call chain cost too much CPU time, it seems we need to adjust the system parameters.

![image](https://user-images.githubusercontent.com/504447/141028833-c4281915-7d62-430f-88b9-2ef71dae7179.png)

**Comment by localvar** [comment]
Hi @gw123 , as we discussed through Wechat, a higher latency of backend service requires a larger `maxIdleConnsPerHost`, otherwise, many connections enter `TIME_WAIT` state and then slow down the dial operation when there are too few free ports.

And in the pressure test, because the pressure exceeds the upper limit of the backend service, the latency is actually higher than the value specified in the request. This leads to the drop of the QPS.

I will close the issue since pr #362 has exposed the `maxIdleConnsPerHost` option to users. And propose to use a TimeLimiter/RateLimiter/CircuitBreaker in the pipeline to mitigate the impaction of a backend service failure or performance issue.
