### ISSUE TITLE
no doc guide to enable support h2 and h2 without ssl

### ISSUE THREAD

**Issue by sodaRyCN** [megaease/easegress#443]
As the title says, there is no document to guide how to open the proxy of H2/H2C, and I am sure that H2 is not turned on by default

**Comment by localvar** [comment]
hi @sodaRyCN , Easegress is based on the standard HTTP package of Golang which has transparent support for the HTTP/2 protocol when using HTTPS from Go 1.6, which means HTTP/2 is enabled when [https](https://github.com/megaease/easegress/blob/main/doc/reference/controllers.md#httpserver) is set to true.

And Easegress don't support h2c, that's why we don't have an option to enable it.

**Comment by sodaRyCN** [comment]
I got it.

so How should I set up the proxy while I use grpc protocol. Easegress support grpc protocol. and grpc is based on http2 and support no tls.

**Comment by localvar** [comment]
We have a plan to support gRPC, but it is not ready now.
Please let us know if you find we mentioned gRPC support in our document, we will update it.

**Comment by sodaRyCN** [comment]
oh, sorry.  it is Ease Service instead of Easegress that supports grpc protocol.

thanks for your replay
