### ISSUE TITLE
Inconsistent processing logic for `matchMethod` and `matchHeaders` in `mux.ServeHTTP`.

### ISSUE THREAD

**Issue by aniaan** [megaease/easegress#535]
**Describe the bug**

When I was looking at the code of `mux.ServeHTTP`, I found that the logic regarding the processing of `matchMethod` is not consistent with the logic of `matchHeaders`, the specific code range is https://github.com/megaease/easegress/blob/36480f34946b464820360ea1a535880fd7e7751f/pkg/object/httpserver/mux.go#L385-L426,

The execution flow here is as follows:
<img width="1377" alt="截屏2022-03-08 下午8 18 22" src="https://user-images.githubusercontent.com/40813941/157236798-59a2618a-fcea-4143-be47-f0e456f2601b.png">

From the figure, we can see that in the case of `matchMethod=false`, the request will be responded directly, and in the case of `matchHeaders=false`, the next cycle will be performed, and the processing behavior of these two is inconsistent.

**Expected behavior**

I think the logic should be the same when `matchMethod` and `matchHeader` processing result is `false`, either it will go to the `next round of loop` or `respond directly to the failed request`.

I think it's better to go to the next round of the cycle, so that the following configuration can be achieved

```yaml
rules:
  - paths:
    - pathPrefix: /pipeline
      method: GET
      backend: get-demo
    
    - pathPrefix: /pipeline
      method: POST
      backend: post-demo
```

**Version**

master

**Configuration**
* Easegress Configuration
```yaml
```

* HTTP server configuration
```yaml
```

* Pipeline Configuration
```yaml
```

**Logs**
```
Easegress logs, if applicable.
```

**OS and Hardware**
 - OS: [e.g. Ubuntu 20.04]
 - CPU:[e.g. Intel(R) Core(TM) i5-8265U]
 - Memory: [e.g. 16GB]

**Additional context**

---
Thanks for contributing 🎉!

**Comment by xxx7xxxx** [comment]
This ain't a bug, because the behavior is expected. But I agree with your judgment about consistency. The failure of supporting different methods for the same pipeline was designed in considering the core role of `path` in RESTful API style. But as a general gateway, I think your choice is right, we should support the config you wrote.

As for why headers not matched leads to next loop is the requirement driven, [EaseMesh](https://github.com/megaease/easemesh/) use headers to route to different services. 

Anyway, we will fix it, thx for the report.
