### ISSUE TITLE
Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [megaease/easegress#787]
Hi!

Could you please put the information about supported architectures to the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know). Maybe some kind of table "OS-Arch" will be better. I am mostly interested in ARM support.

This kind of information is important for the end-users.

Thanks in advance!

**Comment by localvar** [comment]
@zamazan4ik , our official released binaries only support 386 and amd64 by now. But Easegress is built by Go, so it should support all architectures supported by Go, including ARM.

the only exception is the [WASM](https://github.com/megaease/easegress/blob/main/doc/reference/filters.md#wasmhost) feature because it depends on a third-party package which we think only supports amd64, but this feature is disabled by default.

We will follow your suggestion to document the supported architectures, thanks.
